version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.11-browsers
        environment:          
          DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - checkout

      - run: google-chrome --version 89.0.4389.23
      
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "./node_modules"

      - run:
          name: NPM Install
          command: |
            npm install

      - run:
          name: Test Run
          command: |
            npm run e2e
            
      - store_artifacts:
          path: e2e/test-reports/cucumber-test-results.html
